### ISSUE TITLE
Add netlify deployment with example data

### ISSUE THREAD

**Issue by LaChope** [kbss-cvut/csat-maintenance-planner#173]
A/C:
- netlify deployment is running and there is a link to it from README file
- within the deployment Keycloak authorization is disabled (i believe there is env DEVELOPMENT for that purpose)
- Planer shows anonymized/artificial data

**Comment by blcham** [comment]
@LaChope I made it public, let me know if it was a mistake.

**Comment by blcham** [comment]
@LaChope A/C's are not satisfied:
> netlify deployment is running and there is a link to it from README file

**Comment by LaChope** [comment]
It is not deployed yet, there are still issues with netlify
